<?php 


return [
    'home_en' => 'Home',
    'home_hi' => 'घर',
    'wtowonsg_en'=>'Welcome to Official Website of National Security Guard',
    'wtowonsg_hi'=>'राष्ट्रीय सुरक्षा गार्ड की आधिकारिक वेबसाइट में आपका स्वागत है',
    'Sitemap_en' => 'Sitemap',
    'Sitemap_hi'=> 'साइट मैप',
    'Feedback_en'=> 'Feedback',
    'Feedback_hi'=> 'प्रतिक्रिया',
    'sra_en'=> 'Screen Reader Access',
    'sra_hi'=> 'स्क्रीन रीडर एक्सेस',
    'stmc_en'=> 'Skip to Main Content',
    'stmc_hi'=> 'मुख्य विषयवस्तु में जाएं',
    'nau_en'=> 'News and Updates',
    'nau_hi'=> 'समाचार और अद्यतन',
    'View_All_en'=> 'View All',
    'View_All_hi'=> 'सभी को देखें',
    'ln_en'=> 'Latest News',
    'ln_hi'=> 'ताजा खबर',
    'ba_en'=> 'Browse All',
    'ba_hi'=> 'सभी ब्राउज़ करें',
    'Achievements_en'=> 'Achievements',
    'Achievements_hi'=> 'उपलब्धियों',
    'Continue_en'=> 'Continue',
    'Continue_hi'=> 'जारी रखना',
    'nsgte_en'=> 'NSG:The Eliminators',
    'nsgte_hi'=> 'एनएसजी: एलिमिनेटर',
    'pg_en'=> 'Photo Gallery',
    'pg_hi'=> 'फोटो गैलरी',
    'rfncnc_en'=> 'Register for NCNC',
    'rfncnc_hi'=> 'एनसीएनसी के लिए पंजीकरण करें',
    'No_Data_Available_en'=> 'No Data Available',
    'No_Data_Available_hi'=> 'कोई डेटा मौजूद नहीं',
    '404_en'=> 'The page you are looking for is not found',
    '404_hi'=> 'आप जिस पृष्ठ की तलाश कर रहे हैं वह नहीं मिला है',
    'comingsoon_en' => 'Coming Soon',
    'comingsoon_hi' => 'जल्द आ रहा है',
    
];