<?php 


return [
    'home_en' => 'Home',
    'home_hi' => 'घर',
    'wtowonsg_en'=>'Welcome to Official Website of National Security Guard',
    'wtowonsg_hi'=>'राष्ट्रीय सुरक्षा गार्ड की आधिकारिक वेबसाइट में आपका स्वागत है',
    'Sitemap_en' => 'Sitemap',
    'Sitemap_hi'=> 'साइट मैप',
    'Feedback_en'=> 'Feedback',
    'Feedback_hi'=> 'प्रतिक्रिया',
    'sra_en'=> 'Screen Reader Access',
    'sra_hi'=> 'स्क्रीन रीडर एक्सेस',
    'stmc_en'=> 'Skip to Main Content',
    'stmc_hi'=> 'मुख्य विषयवस्तु में जाएं',
    'nau_en'=> 'News and Updates',
    'nau_hi'=> 'समाचार और अद्यतन',
    'View_All_en'=> 'View All',
    'View_All_hi'=> 'सभी को देखें',
    'ln_en'=> 'Latest News',
    'ln_hi'=> 'ताजा खबर',
    'ba_en'=> 'Browse All',
    'ba_hi'=> 'सभी ब्राउज़ करें',
    'Achievements_en'=> 'Achievements',
    'Achievements_hi'=> 'उपलब्धियों',
    'Continue_en'=> 'Continue',
    'Continue_hi'=> 'जारी रखना',
    'nsgte_en'=> 'NSG:The Eliminators',
    'nsgte_hi'=> 'एनएसजी: एलिमिनेटर',
    'pg_en'=> 'Photo Gallery',
    'pg_hi'=> 'फोटो गैलरी',
    'rfncnc_en'=> 'Register for NCNC',
    'rfncnc_hi'=> 'एनसीएनसी के लिए पंजीकरण करें',
    'No_Data_Available_en'=> 'No Data Available',
    'No_Data_Available_hi'=> 'कोई डेटा मौजूद नहीं',
    '404_en'=> 'The page you are looking for is not found',
    '404_hi'=> 'आप जिस पृष्ठ की तलाश कर रहे हैं वह नहीं मिला है',
    'comingsoon_en' => 'Coming Soon',
    'comingsoon_hi' => 'जल्द आ रहा है',
    'VisitorCounte_en'=>'Visitor Counter ',
    'VisitorCounte_hi'=>'कुल विज़िटर',
    'LastUpdated_en'=>'Last Updated',
    'LastUpdated_hi'=>'आखरी अपडेट',
    'Our_Martyrs_en'=>'Our Martyrs',
    'Our_Martyrs_hi'=>'हमारे शहीद',
    'Our_Martyrs_Pride_of_the_Nation_en' => 'Our Martyrs - "Pride of the Nation"',
    'Our_Martyrs_Pride_of_the_Nation_hi' => 'हमारे शहीद - "राष्ट्र का गौरव।"',
    'The_National_Security_Guard_en' => 'The National Security Guard',
    'The_National_Security_Guard_hi' => 'राष्ट्रीय सुरक्षा गार्ड',
    'The_National_Security_Guard_description_en' => ' NSG is Federal Contingency World Class Zero Error Force to deal with anti-terrorist activities in all its manifestation. The NSG is a Force specially equipped and trained to deal with specific situations and is therefore, to be used only in exceptional circumstances to thwart serious acts of terrorism.',
    'The_National_Security_Guard_description_hi' => 'एनएसजी आतंकवाद विरोधी गतिविधियों से निपटने के लिए संघीय आकस्मिक विश्व स्तरीय शून्य त्रुटि बल है। एनएसजी विशिष्ट परिस्थितियों से निपटने के लिए विशेष रूप से सुसज्जित और प्रशिक्षित एक बल है और इसलिए, आतंकवाद के गंभीर कृत्यों को विफल करने के लिए केवल असाधारण परिस्थितियों में ही इसका उपयोग किया जा सकता है।',
    'Honours_Awards_en' => 'Honours & Awards',
    'Honours_Awards_hi' => 'सम्मान एवं पुरस्कार',
    'Honours_Awards_description_en' => 'Recogntion of Gallant, hard work & dedication towards the Nation.',
    'Honours_Awards_description_hi' => 'राष्ट्र के प्रति वीरता, कड़ी मेहनत और समर्पण की पहचान।',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    
];